### ISSUE TITLE
add-in not listed in Gallery anymore

### ISSUE THREAD

**Issue by alanhamlett** [CodeCavePro/monodevelop-wakatime#9] opened 2016-06-23 16:32 UTC
http://addins.monodevelop.com/Project/Index/183 exists but somehow it's not listed when searching the Add-Ins Gallery inside Xamarin Studio.

**Comment by tschoffelen** [comment] 2016-06-23 18:38
Seems to be because the add-in only supports MonoDevelop 5.0, whereas Xamarin Studio currently is 6.0. At least, that's the error I get when trying to install it manually.

**Comment by ghost** [comment] 2016-07-04 08:00
Any news on the issue?

**Comment by salaros** [comment] 2016-07-04 08:12
Actually it needs few more tweaks, I will update the addin today and will publish a new version for Xamarin 6.0

**Comment by Corstiaan84** [comment] 2016-07-15 14:22
Really missing my WakaTime plugin for Xamarin 6 😢 ... Any news? Keep up the great work!

**Comment by salaros** [comment] 2016-08-07 18:03
Hi guys! Sorry, I was on a long trip :) So WakaTime for Xamarin Studio 6.0 for Mac works well,
while WakaTime for Xamarin Studio 6.0 for Windows has a server-side add-in packaging problem:
if you build it locally and install .mpack file everything works, but .mpack file generated by MonoDevelop Add-in repository contains a wrong copy of Mono.Posix.dll (I'm working on it)

**Comment by salaros** [comment] 2016-08-07 18:32
OK, both Windows and Mac OS X builds work. I will try to build MonoDevelop 6.0/6.1 from sources and test it on Linux as well

**Comment by salaros** [comment] 2016-08-12 21:40
I also tested 2.0.1 add-in on MonoDevelop 6.1.x on Debian and it worked

**Comment by Corstiaan84** [comment] 2016-10-10 08:10
I still can't find the plugin in the add-in's screen of Xamarin Studio 6... Any gotchas I am not aware of?

**Comment by salaros** [comment] 2016-10-10 09:14
Could you please add some information about your platform and version of Xamarin Studio? (for example Mac OS X, Xamarin Studio ver 6.1)

**Comment by Corstiaan84** [comment] 2016-10-10 09:15
I am on Mac OS X, using Xamarin Studio 6.1.1 build 15 :-)

**Comment by salaros** [comment] 2016-10-10 09:19
OK, thanks! I will check it on my Mac Pro ASAP (I'm currently out of office)

**Comment by salaros** [comment] 2016-10-24 08:16
Unfortunately I haven't managed to reproduce your issue :(
Please try checking your addin repository settings (make sure you have **stable** channel turned on/checked)

![wakatime xs 611](https://cloud.githubusercontent.com/assets/675348/19638081/e17d4d56-99da-11e6-9e01-fb88b276ebac.png)

**Comment by Corstiaan84** [comment] 2017-02-07 22:20
@salaros Thanks. Still cant find it... Can you screenshot your add-in repository urls? Thanks!

**Comment by alanhamlett** [comment] 2017-02-13 20:17
Seems it's not listed on http://addins.monodevelop.com/ yet, maybe it requires approval from the Monodevelop team?

**Comment by sergey-tihon** [comment] 2017-02-13 21:16
I cannot install it from VS for Mac as well (Vs4Mac uses MonoDevelop 7.0 channel) 
<img width="1024" alt="screen shot 2017-02-14 at 12 12 30 am" src="https://cloud.githubusercontent.com/assets/1197905/22903736/b59cb44c-f24a-11e6-86e9-81d5a807ee2f.png">

**Comment by alanhamlett** [comment] 2017-02-26 08:31
It should be available now: http://addins.monodevelop.com/Project/Index/278

**Comment by salaros** [comment] 2017-02-26 10:28
Hi everybody,
I was on a business trip, so couldn't access my Mac at home. First of all MonoDevelop/XS addin has been published to the "Stable" channel time ago and it seems that lots of Mac users have downloaded it.

![monodevelop 5 6](https://cloud.githubusercontent.com/assets/675348/23338852/4fd91d68-fc26-11e6-95bd-24947f9d5e56.jpg)

@alanhamlett could you explain what was the problem and how did you manage to fix it? So I can apply this fix on the main addin listing.

As for Visual Studio for Mac compatibility - its APIs has changed a lot, I've tried to recompile WakaTime addin for it right after VS for Mac Preview 1 release, but couldn't figure out the new dependencies, so I decided to postpone this task until the first stable release of the new IDE + I'm not sure that MonoDevelop / XS [addin builder](http://addins.monodevelop.com/) is capable yet of automatically building VS for Mac addins.

**Comment by alanhamlett** [comment] 2017-02-26 23:01
I just added a new `Add-in` using `https://github.com/wakatime/monodevelop-wakatime` as the repo field, since I thought the previous `Add-in` had been deleted somehow. What are the urls for the existing published Add-ins you've published? Maybe there are duplicates in the gallery?

**Comment by salaros** [comment] 2018-08-13 11:18
I think all gallery-related issues have been fixed with manual addin upload I request from Microsoft

**Closed as completed by salaros** 2018-08-13 11:18 UTC
